name: Build and Deploy
on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:
  merge_group:

env:
  UNITY_LICENSE:
    "<?xml version=\"1.0\" encoding=\"UTF-8\"?><root>\n    <License id=\"Terms\"\
    >\n        <MachineBindings>\n            <Binding Key=\"1\" Value=\"576562626572264761624c65526f7578\"\
    />\n            <Binding Key=\"2\" Value=\"576562626572264761624c65526f7578\"\
    />\n        </MachineBindings>\n        <MachineID Value=\"D7nTUnjNAmtsUMcnoyrqkgIbYdM=\"\
    />\n        <SerialHash Value=\"672c8715643f6486373b8f9be379a95949be17a1\"/>\n\
    \        <Features>\n            <Feature Value=\"33\"/>\n            <Feature\
    \ Value=\"1\"/>\n            <Feature Value=\"12\"/>\n            <Feature Value=\"\
    2\"/>\n            <Feature Value=\"24\"/>\n            <Feature Value=\"3\"/>\n\
    \            <Feature Value=\"36\"/>\n            <Feature Value=\"17\"/>\n  \
    \          <Feature Value=\"19\"/>\n            <Feature Value=\"62\"/>\n    \
    \        <Feature Value=\"60\"/>\n        </Features>\n        <DeveloperData\
    \ Value=\"AQAAAEY0LVJQUkItUjJOVi1RMlo4LU1aV0stVkpBRg==\"/>\n        <SerialMasked\
    \ Value=\"F4-RPRB-R2NV-Q2Z8-MZWK-XXXX\"/>\n        <StartDate Value=\"2023-10-31T00:00:00\"\
    />\n        <StopDate Value=\"2023-11-30T14:51:27\"/>\n        <UpdateDate Value=\"\
    2023-11-01T13:51:25\"/>\n        <InitialActivationDate Value=\"2023-10-31T13:50:56\"\
    />\n        <LicenseVersion Value=\"6.x\"/>\n        <ClientProvidedVersion Value=\"\
    2022.3.8\"/>\n        <AlwaysOnline Value=\"false\"/>\n        <Entitlements>\n\
    \            <Entitlement Ns=\"unity_editor\" Tag=\"UnityPersonal\" Type=\"EDITOR\"\
    \ ValidTo=\"9999-12-31T00:00:00\"/>\n            <Entitlement Ns=\"unity_editor\"\
    \ Tag=\"DarkSkin\" Type=\"EDITOR_FEATURE\" ValidTo=\"9999-12-31T00:00:00\"/>\n\
    \        </Entitlements>\n    </License>\n<Signature xmlns=\"http://www.w3.org/2000/09/xmldsig#\"\
    ><SignedInfo><CanonicalizationMethod Algorithm=\"http://www.w3.org/TR/2001/REC-xml-c14n-20010315#WithComments\"\
    /><SignatureMethod Algorithm=\"http://www.w3.org/2000/09/xmldsig#rsa-sha1\"/><Reference\
    \ URI=\"#Terms\"><Transforms><Transform Algorithm=\"http://www.w3.org/2000/09/xmldsig#enveloped-signature\"\
    /></Transforms><DigestMethod Algorithm=\"http://www.w3.org/2000/09/xmldsig#sha1\"\
    /><DigestValue>H8mBsVqqdYwDgVZh7UHqDcLwxLk=</DigestValue></Reference></SignedInfo><SignatureValue>TN2WLzN0nJN7cR+pHHsrnh7UB9cGSx7F0gfHgyGrSUkib8syZIaJejSdfjeV3lQXMkqLUeTUct4n&#13;\n\
    4g3jHVBafWNMwRy/dMpRJPMCdghesRnpw7fVPJ3R7TbK1ceH3C0MnxDBuzZiBXIt8zQCN0CBEiI3&#13;\n\
    XAiUlonvWgT/VvjNCsMvW2pCumMMCf/QpVShyHh6BPqtCjq/D4g3+A1aaPbxZIeSUojOsM+TbGZq&#13;\n\
    Zj8drTE/MEjE08PXEtk1eoSS6nTt9f5o59HuWuyV27RRmImbZys0UDwiHcpc3asWxryOEorjnXvJ&#13;\n\
    UshQDz1PvkbCpWSt+3X/e/3BWiEIUqBTIPr73A==</SignatureValue></Signature></root>\n"


jobs:
  buildForWindows:
    name: Build for ${{ matrix.targetPlatform }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        targetPlatform:
          - StandaloneWindows
          - StandaloneWindows64
          
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          
      - uses: actions/cache@v3
        with:
          path: Library
          key: Library-${{ matrix.targetPlatform }}

      - name: 유니티 빌드
        uses: game-ci/unity-builder@v3
        env:
          UNITY_EMAIL: rollrat.cse@gmail.com
          UNITY_PASSWORD: Aqwer1234
        with:
          targetPlatform: ${{ matrix.targetPlatform }}
          projectPath: Client
          unityVersion: 2022.3.8f1
          allowDirtyBuild: true
